version: "3.8"

services:
  web:
    container_name: issue-tracker-web
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - 3000:3000
    command: ./docker-entrypoint.sh prod
    restart: unless-stopped
    networks:
      - issue-tracker-network

networks:
  issue-tracker-network:
    external: true